// Generated from info-cache-audit-bindings.json. Read-only, explicit test opt-in.
#include "CvGameCoreDLLPCH.h"
#include "Lua/CvLuaSupport.h"
#include <cstdlib>
#include <cstring>
int LekmodMacReadInfoCache(lua_State* L)
{
 const char* enabled=std::getenv("LEKMOD_CONFIG_AUDIT");
 if (!enabled || std::strcmp(enabled,"1")!=0) return luaL_error(L,"ReadInfoCacheForTest requires the explicit test environment");
 const char* table=luaL_checkstring(L,1);
 const int id=luaL_checkint(L,2);
 if (std::strcmp(table,"Buildings") == 0)
 {
  if (id<0 || id>=static_cast<int>(GC.getNumBuildingInfos())) return luaL_error(L,"info-cache index out of bounds");
  const CvBuildingEntry* info=GC.getBuildingInfo(static_cast<BuildingTypes>(id));
  if (!info) return luaL_error(L,"info-cache entry missing");
  lua_createtable(L,0,96);
  lua_pushboolean(L,info->AffectSpiesNow()); lua_setfield(L,-2,"AffectSpiesNow");
  lua_pushinteger(L,info->GetAirModifier()); lua_setfield(L,-2,"AirModifier");
  lua_pushboolean(L,info->IsAirlift()); lua_setfield(L,-2,"Airlift");
  lua_pushboolean(L,info->AllowsFoodTradeRoutes()); lua_setfield(L,-2,"AllowsFoodTradeRoutes");
  lua_pushboolean(L,info->AllowsProductionTradeRoutes()); lua_setfield(L,-2,"AllowsProductionTradeRoutes");
  lua_pushinteger(L,info->IsAllowsRangeStrike()); lua_setfield(L,-2,"AllowsRangeStrike");
  lua_pushboolean(L,info->AllowsWaterRoutes()); lua_setfield(L,-2,"AllowsWaterRoutes");
  lua_pushboolean(L,info->IsBorderObstacle()); lua_setfield(L,-2,"BorderObstacle");
  lua_pushinteger(L,info->GetBuildingProductionModifier()); lua_setfield(L,-2,"BuildingProductionModifier");
  lua_pushboolean(L,info->IsCapital()); lua_setfield(L,-2,"Capital");
  lua_pushinteger(L,info->GetCapturePlunderModifier()); lua_setfield(L,-2,"CapturePlunderModifier");
  lua_pushinteger(L,info->GetCityConnectionTradeRouteModifier()); lua_setfield(L,-2,"CityConnectionTradeRouteModifier");
  lua_pushinteger(L,info->GetCityStateTradeRouteGoldModifier()); lua_setfield(L,-2,"CityStateTradeRouteGoldModifier");
  lua_pushinteger(L,info->GetCityStateTradeRouteProductionModifier()); lua_setfield(L,-2,"CityStateTradeRouteProductionModifier");
  lua_pushboolean(L,info->IsCityWall()); lua_setfield(L,-2,"CityWall");
  lua_pushinteger(L,info->GetConquestProbability()); lua_setfield(L,-2,"ConquestProb");
  lua_pushinteger(L,info->GetProductionCost()); lua_setfield(L,-2,"Cost");
  lua_pushinteger(L,info->GetDefenseModifier()); lua_setfield(L,-2,"Defense");
  lua_pushboolean(L,info->IsEspionage()); lua_setfield(L,-2,"Espionage");
  lua_pushinteger(L,info->GetEspionageModifier()); lua_setfield(L,-2,"EspionageModifier");
  lua_pushinteger(L,info->GetExcessGrowth()); lua_setfield(L,-2,"ExcessGrowth");
  lua_pushinteger(L,info->GetExtraCityHitPoints()); lua_setfield(L,-2,"ExtraCityHitPoints");
  lua_pushinteger(L,info->GetExtraLeagueVotes()); lua_setfield(L,-2,"ExtraLeagueVotes");
  lua_pushinteger(L,info->GetExtraMissionarySpreads()); lua_setfield(L,-2,"ExtraMissionarySpreads");
  lua_pushinteger(L,info->GetExtraSpies()); lua_setfield(L,-2,"ExtraSpies");
  lua_pushinteger(L,info->GetFaithCost()); lua_setfield(L,-2,"FaithCost");
  lua_pushinteger(L,info->GetFirstPurchaseDiscount()); lua_setfield(L,-2,"FirstPurchaseDiscount");
  lua_pushinteger(L,info->GetFoodKept()); lua_setfield(L,-2,"FoodKept");
  lua_pushinteger(L,info->GetFreeGreatWorkCount()); lua_setfield(L,-2,"FreeGreatWorkCount");
  lua_pushinteger(L,info->GetFreePolicies()); lua_setfield(L,-2,"FreePolicies");
  lua_pushinteger(L,info->GetFreeTechs()); lua_setfield(L,-2,"FreeTechs");
  lua_pushboolean(L,info->IsFreshWater()); lua_setfield(L,-2,"FreshWater");
  lua_pushboolean(L,info->IsGarrisonMaintenanceFree()); lua_setfield(L,-2,"GarrisonMaintenceFree");
  lua_pushinteger(L,info->GetGarrisonStrengthBonus()); lua_setfield(L,-2,"GarrisonStrengthBonus");
  lua_pushinteger(L,info->GetGlobalDefenseModifier()); lua_setfield(L,-2,"GlobalDefenseMod");
  lua_pushinteger(L,info->GetGlobalEspionageModifier()); lua_setfield(L,-2,"GlobalEspionageModifier");
  lua_pushinteger(L,info->GetGlobalGreatPeopleRateModifier()); lua_setfield(L,-2,"GlobalGreatPeopleRateModifier");
  lua_pushinteger(L,info->GetGlobalPlotBuyCostModifier()); lua_setfield(L,-2,"GlobalPlotBuyCostModifier");
  lua_pushinteger(L,info->GetGlobalPlotCultureCostModifier()); lua_setfield(L,-2,"GlobalPlotCultureCostModifier");
  lua_pushinteger(L,info->GetGlobalPopulationChange()); lua_setfield(L,-2,"GlobalPopulationChange");
  lua_pushinteger(L,info->GetGlobalSpaceProductionModifier()); lua_setfield(L,-2,"GlobalSpaceProductionModifier");
  lua_pushinteger(L,info->GetGold()); lua_setfield(L,-2,"Gold");
  lua_pushinteger(L,info->GetGoldCost()); lua_setfield(L,-2,"GoldCost");
  lua_pushinteger(L,info->GetGoldMaintenance()); lua_setfield(L,-2,"GoldMaintenance");
  lua_pushboolean(L,info->IsGoldenAge()); lua_setfield(L,-2,"GoldenAge");
  lua_pushinteger(L,info->GetGoldenAgeModifier()); lua_setfield(L,-2,"GoldenAgeModifier");
  lua_pushinteger(L,info->GetGreatPeopleRateChange()); lua_setfield(L,-2,"GreatPeopleRateChange");
  lua_pushinteger(L,info->GetGreatPeopleRateModifier()); lua_setfield(L,-2,"GreatPeopleRateModifier");
  lua_pushinteger(L,info->GetGreatScientistBeakerModifier()); lua_setfield(L,-2,"GreatScientistBeakerModifier");
  lua_pushinteger(L,info->GetGreatWorkCount()); lua_setfield(L,-2,"GreatWorkCount");
  lua_pushinteger(L,info->GetGreatWorkHappiness()); lua_setfield(L,-2,"GreatWorkHappiness");
  lua_pushinteger(L,info->GetGreatWorkMilitaryProductionModifier()); lua_setfield(L,-2,"GreatWorkMilitaryProductionModifier");
  lua_pushinteger(L,info->GetGreatWorksTourismModifier()); lua_setfield(L,-2,"GreatWorksTourismModifier");
  lua_pushinteger(L,info->GetHappiness()); lua_setfield(L,-2,"Happiness");
  lua_pushinteger(L,info->GetHappinessPerCity()); lua_setfield(L,-2,"HappinessPerCity");
  lua_pushinteger(L,info->GetHappinessPerXPolicies()); lua_setfield(L,-2,"HappinessPerXPolicies");
  lua_pushboolean(L,info->IsRequiresHolyCity()); lua_setfield(L,-2,"HolyCity");
  lua_pushinteger(L,info->GetHurryCostModifier()); lua_setfield(L,-2,"HurryCostModifier");
  lua_pushinteger(L,info->GetInstantMilitaryIncrease()); lua_setfield(L,-2,"InstantMilitaryIncrease");
  lua_pushinteger(L,info->GetInstantSpyRankChange()); lua_setfield(L,-2,"InstantSpyRankChange");
  lua_pushboolean(L,info->IsReligious()); lua_setfield(L,-2,"IsReligious");
  lua_pushboolean(L,info->IsLake()); lua_setfield(L,-2,"Lake");
  lua_pushinteger(L,info->GetLandmarksTourismPercent()); lua_setfield(L,-2,"LandmarksTourismPercent");
  lua_pushinteger(L,info->GetLocalPopulationChange()); lua_setfield(L,-2,"LocalPopulationChange");
  lua_pushboolean(L,info->IsMalianTreasury()); lua_setfield(L,-2,"MaliTreasury");
  lua_pushinteger(L,info->GetMilitaryProductionMod()); lua_setfield(L,-2,"MilitaryProductionMod");
  lua_pushinteger(L,info->GetMilitaryProductionModifier()); lua_setfield(L,-2,"MilitaryProductionModifier");
  lua_pushinteger(L,info->GetMinAreaSize()); lua_setfield(L,-2,"MinAreaSize");
  lua_pushinteger(L,info->GetMutuallyExclusiveGroup()); lua_setfield(L,-2,"MutuallyExclusiveGroup");
  lua_pushinteger(L,info->IsNearbyMountainRequired()); lua_setfield(L,-2,"NearbyMountainRequired");
  lua_pushboolean(L,info->IsNeverCapture()); lua_setfield(L,-2,"NeverCapture");
  lua_pushboolean(L,info->IsNoOccupiedUnhappiness()); lua_setfield(L,-2,"NoOccupiedUnhappiness");
  lua_pushboolean(L,info->IsNukeImmune()); lua_setfield(L,-2,"NukeImmune");
  lua_pushinteger(L,info->GetNukeModifier()); lua_setfield(L,-2,"NukeModifier");
  lua_pushboolean(L,info->NullifyInfluenceModifier()); lua_setfield(L,-2,"NullifyInfluenceModifier");
  lua_pushinteger(L,info->GetNumCityCostMod()); lua_setfield(L,-2,"NumCityCostMod");
  lua_pushinteger(L,info->GetNumTradeRouteBonus()); lua_setfield(L,-2,"NumTradeRouteBonus");
  lua_pushinteger(L,info->GetPlotBuyCostModifier()); lua_setfield(L,-2,"PlotBuyCostModifier");
  lua_pushinteger(L,info->GetPlotCultureCostModifier()); lua_setfield(L,-2,"PlotCultureCostModifier");
  lua_pushinteger(L,info->GetPolicyCostModifier()); lua_setfield(L,-2,"PolicyCostModifier");
  lua_pushinteger(L,info->GetReligiousPressureModifier()); lua_setfield(L,-2,"ReligiousPressureModifier");
  lua_pushboolean(L,info->IsRiver()); lua_setfield(L,-2,"River");
  lua_pushboolean(L,info->IsSellable()); lua_setfield(L,-2,"Sellable");
  lua_pushinteger(L,info->GetSpaceProductionModifier()); lua_setfield(L,-2,"SpaceProductionModifier");
  lua_pushinteger(L,info->GetSpecialistCount()); lua_setfield(L,-2,"SpecialistCount");
  lua_pushinteger(L,info->GetSpyRankChange()); lua_setfield(L,-2,"SpyRankChange");
  lua_pushinteger(L,info->GetTradeRouteLandDistanceModifier()); lua_setfield(L,-2,"TradeRouteLandDistanceModifier");
  lua_pushinteger(L,info->GetTradeRouteSeaDistanceModifier()); lua_setfield(L,-2,"TradeRouteSeaDistanceModifier");
  lua_pushinteger(L,info->GetUnhappinessModifier()); lua_setfield(L,-2,"UnhappinessModifier");
  lua_pushinteger(L,info->GetUnitUpgradeCostMod()); lua_setfield(L,-2,"UnitUpgradeCostMod");
  lua_pushboolean(L,info->IsUnlockedByBelief()); lua_setfield(L,-2,"UnlockedByBelief");
  lua_pushboolean(L,info->IsUnlockedByLeague()); lua_setfield(L,-2,"UnlockedByLeague");
  lua_pushinteger(L,info->GetUnmoddedHappiness()); lua_setfield(L,-2,"UnmoddedHappiness");
  lua_pushboolean(L,info->IsWater()); lua_setfield(L,-2,"Water");
  lua_pushinteger(L,info->GetWorkerSpeedModifier()); lua_setfield(L,-2,"WorkerSpeedModifier");
  lua_pushinteger(L,info->GetXBuiltTriggersIdeologyChoice()); lua_setfield(L,-2,"XBuiltTriggersIdeologyChoice");
  return 1;
 }
 if (std::strcmp(table,"Units") == 0)
 {
  if (id<0 || id>=static_cast<int>(GC.getNumUnitInfos())) return luaL_error(L,"info-cache index out of bounds");
  const CvUnitEntry* info=GC.getUnitInfo(static_cast<UnitTypes>(id));
  if (!info) return luaL_error(L,"info-cache entry missing");
  lua_createtable(L,0,58);
  lua_pushinteger(L,info->GetAdvancedStartCost()); lua_setfield(L,-2,"AdvancedStartCost");
  lua_pushinteger(L,info->GetAirInterceptRange()); lua_setfield(L,-2,"AirInterceptRange");
  lua_pushinteger(L,info->GetAirUnitCap()); lua_setfield(L,-2,"AirUnitCap");
  lua_pushboolean(L,info->IsAnyIdeologyUnlock()); lua_setfield(L,-2,"AnyIdeologyUnlock");
  lua_pushinteger(L,info->GetBaseBeakersTurnsToCount()); lua_setfield(L,-2,"BaseBeakersTurnsToCount");
  lua_pushinteger(L,info->GetBaseCultureTurnsToCount()); lua_setfield(L,-2,"BaseCultureTurnsToCount");
  lua_pushinteger(L,info->GetBaseGold()); lua_setfield(L,-2,"BaseGold");
  lua_pushinteger(L,info->GetBaseHurry()); lua_setfield(L,-2,"BaseHurry");
  lua_pushinteger(L,info->GetBaseSightRange()); lua_setfield(L,-2,"BaseSightRange");
  lua_pushboolean(L,info->IsCanBuyCityState()); lua_setfield(L,-2,"CanBuyCityState");
  lua_pushinteger(L,info->GetCombat()); lua_setfield(L,-2,"Combat");
  lua_pushinteger(L,info->GetCombatLimit()); lua_setfield(L,-2,"CombatLimit");
  lua_pushinteger(L,info->GetConscriptionValue()); lua_setfield(L,-2,"Conscription");
  lua_pushinteger(L,info->GetProductionCost()); lua_setfield(L,-2,"Cost");
  lua_pushinteger(L,info->GetFaithCost()); lua_setfield(L,-2,"FaithCost");
  lua_pushboolean(L,info->IsFoodProduction()); lua_setfield(L,-2,"Food");
  lua_pushboolean(L,info->IsFound()); lua_setfield(L,-2,"Found");
  lua_pushboolean(L,info->IsFoundAbroad()); lua_setfield(L,-2,"FoundAbroad");
  lua_pushboolean(L,info->IsFoundReligion()); lua_setfield(L,-2,"FoundReligion");
  lua_pushinteger(L,info->GetGoldenAgeTurns()); lua_setfield(L,-2,"GoldenAgeTurns");
  lua_pushinteger(L,info->GetHurryCostModifier()); lua_setfield(L,-2,"HurryCostModifier");
  lua_pushinteger(L,info->GetHurryMultiplier()); lua_setfield(L,-2,"HurryMultiplier");
  lua_pushinteger(L,info->IsImmobile()); lua_setfield(L,-2,"Immobile");
  lua_pushinteger(L,info->GetLocalPopChange()); lua_setfield(L,-2,"LocalPopChange");
  lua_pushboolean(L,info->IsMechUnit()); lua_setfield(L,-2,"Mechanized");
  lua_pushboolean(L,info->IsMilitaryProduction()); lua_setfield(L,-2,"MilitaryProduction");
  lua_pushboolean(L,info->IsMilitarySupport()); lua_setfield(L,-2,"MilitarySupport");
  lua_pushinteger(L,info->GetMinAreaSize()); lua_setfield(L,-2,"MinAreaSize");
  lua_pushboolean(L,info->CanMoveAfterPurchase()); lua_setfield(L,-2,"MoveAfterPurchase");
  lua_pushinteger(L,info->GetMoves()); lua_setfield(L,-2,"Moves");
  lua_pushboolean(L,info->IsNoBadGoodies()); lua_setfield(L,-2,"NoBadGoodies");
  lua_pushboolean(L,info->IsNoMaintenance()); lua_setfield(L,-2,"NoMaintenance");
  lua_pushinteger(L,info->GetNukeDamageLevel()); lua_setfield(L,-2,"NukeDamageLevel");
  lua_pushinteger(L,info->GetNumExoticGoods()); lua_setfield(L,-2,"NumExoticGoods");
  lua_pushinteger(L,info->GetNumGoldPerEra()); lua_setfield(L,-2,"NumGoldPerEra");
  lua_pushinteger(L,info->GetOneShotTourism()); lua_setfield(L,-2,"OneShotTourism");
  lua_pushinteger(L,info->GetOneShotTourismPercentOthers()); lua_setfield(L,-2,"OneShotTourismPercentOthers");
  lua_pushboolean(L,info->IsPillage()); lua_setfield(L,-2,"Pillage");
  lua_pushinteger(L,info->GetPopulationReq()); lua_setfield(L,-2,"PopulationReq");
  lua_pushboolean(L,info->IsPrereqResources()); lua_setfield(L,-2,"PrereqResources");
  lua_pushboolean(L,info->IsProhibitsSpread()); lua_setfield(L,-2,"ProhibitsSpread");
  lua_pushboolean(L,info->IsPurchaseOnly()); lua_setfield(L,-2,"PurchaseOnly");
  lua_pushinteger(L,info->GetRange()); lua_setfield(L,-2,"Range");
  lua_pushboolean(L,info->IsRangeAttackOnlyInDomain()); lua_setfield(L,-2,"RangeAttackOnlyInDomain");
  lua_pushinteger(L,info->GetRangedCombat()); lua_setfield(L,-2,"RangedCombat");
  lua_pushinteger(L,info->GetRangedCombatLimit()); lua_setfield(L,-2,"RangedCombatLimit");
  lua_pushinteger(L,info->GetReligionSpreads()); lua_setfield(L,-2,"ReligionSpreads");
  lua_pushinteger(L,info->GetReligiousStrength()); lua_setfield(L,-2,"ReligiousStrength");
  lua_pushboolean(L,info->IsRemoveHeresy()); lua_setfield(L,-2,"RemoveHeresy");
  lua_pushboolean(L,info->IsRequiresEnhancedReligion()); lua_setfield(L,-2,"RequiresEnhancedReligion");
  lua_pushboolean(L,info->IsRequiresFaithPurchaseEnabled()); lua_setfield(L,-2,"RequiresFaithPurchaseEnabled");
  lua_pushinteger(L,info->GetSettlerCostModifier()); lua_setfield(L,-2,"SettlerCostModifier");
  lua_pushboolean(L,info->IsSpreadReligion()); lua_setfield(L,-2,"SpreadReligion");
  lua_pushboolean(L,info->IsSuicide()); lua_setfield(L,-2,"Suicide");
  lua_pushboolean(L,info->IsTrade()); lua_setfield(L,-2,"Trade");
  lua_pushinteger(L,info->GetWorkRate()); lua_setfield(L,-2,"WorkRate");
  lua_pushinteger(L,info->GetXPValueAttack()); lua_setfield(L,-2,"XPValueAttack");
  lua_pushinteger(L,info->GetXPValueDefense()); lua_setfield(L,-2,"XPValueDefense");
  return 1;
 }
 if (std::strcmp(table,"UnitPromotions") == 0)
 {
  if (id<0 || id>=static_cast<int>(GC.getNumPromotionInfos())) return luaL_error(L,"info-cache index out of bounds");
  const CvPromotionEntry* info=GC.getPromotionInfo(static_cast<PromotionTypes>(id));
  if (!info) return luaL_error(L,"info-cache entry missing");
  lua_createtable(L,0,105);
  lua_pushinteger(L,info->GetAdjacentTileHealChange()); lua_setfield(L,-2,"AdjacentTileHealChange");
  lua_pushboolean(L,info->IsAirSweepCapable()); lua_setfield(L,-2,"AirSweepCapable");
  lua_pushinteger(L,info->GetAirSweepCombatModifier()); lua_setfield(L,-2,"AirSweepCombatModifier");
  lua_pushboolean(L,info->IsAllowsEmbarkation()); lua_setfield(L,-2,"AllowsEmbarkation");
  lua_pushboolean(L,info->IsAlwaysHeal()); lua_setfield(L,-2,"AlwaysHeal");
  lua_pushboolean(L,info->IsAmphib()); lua_setfield(L,-2,"Amphib");
  lua_pushinteger(L,info->GetAttackExtraMoves()); lua_setfield(L,-2,"AttackExtraMoves");
  lua_pushinteger(L,info->GetAttackFortifiedMod()); lua_setfield(L,-2,"AttackFortifiedMod");
  lua_pushinteger(L,info->GetAttackMod()); lua_setfield(L,-2,"AttackMod");
  lua_pushinteger(L,info->GetAttackWoundedMod()); lua_setfield(L,-2,"AttackWoundedMod");
  lua_pushboolean(L,info->IsCanMoveAfterAttacking()); lua_setfield(L,-2,"CanMoveAfterAttacking");
  lua_pushboolean(L,info->CanMoveAllTerrain()); lua_setfield(L,-2,"CanMoveAllTerrain");
  lua_pushboolean(L,info->IsCanMoveImpassable()); lua_setfield(L,-2,"CanMoveImpassable");
  lua_pushboolean(L,info->IsCannotBeChosen()); lua_setfield(L,-2,"CannotBeChosen");
  lua_pushinteger(L,info->GetCapitalDefenseFalloff()); lua_setfield(L,-2,"CapitalDefenseFalloff");
  lua_pushinteger(L,info->GetCapitalDefenseModifier()); lua_setfield(L,-2,"CapitalDefenseModifier");
  lua_pushboolean(L,info->IsCaptureDefeatedEnemy()); lua_setfield(L,-2,"CaptureDefeatedEnemy");
  lua_pushinteger(L,info->GetCargoChange()); lua_setfield(L,-2,"CargoChange");
  lua_pushinteger(L,info->GetCityAttackPercent()); lua_setfield(L,-2,"CityAttack");
  lua_pushboolean(L,info->IsCityAttackOnly()); lua_setfield(L,-2,"CityAttackOnly");
  lua_pushinteger(L,info->GetCityAttackPlunderModifier()); lua_setfield(L,-2,"CityAttackPlunderModifier");
  lua_pushinteger(L,info->GetCityAttackMovePenalty()); lua_setfield(L,-2,"CityMovementPenalty");
  lua_pushinteger(L,info->GetCombatDifferentIdeology()); lua_setfield(L,-2,"CombatDifferentIdeology");
  lua_pushinteger(L,info->GetCombatPercent()); lua_setfield(L,-2,"CombatPercent");
  lua_pushinteger(L,info->GetDefenseMod()); lua_setfield(L,-2,"DefenseMod");
  lua_pushinteger(L,info->GetDropRange()); lua_setfield(L,-2,"DropRange");
  lua_pushinteger(L,info->GetEmbarkDefenseModifier()); lua_setfield(L,-2,"EmbarkDefenseModifier");
  lua_pushinteger(L,info->GetEmbarkExtraVisibility()); lua_setfield(L,-2,"EmbarkExtraVisibility");
  lua_pushboolean(L,info->IsEmbarkedAllWater()); lua_setfield(L,-2,"EmbarkedAllWater");
  lua_pushboolean(L,info->IsEmbarkedUnitReceivesMovement()); lua_setfield(L,-2,"EmbarkedUnitReceivesMovement");
  lua_pushinteger(L,info->GetEnemyDamage()); lua_setfield(L,-2,"EnemyDamage");
  lua_pushinteger(L,info->GetEnemyDamageChance()); lua_setfield(L,-2,"EnemyDamageChance");
  lua_pushinteger(L,info->GetEnemyHealChange()); lua_setfield(L,-2,"EnemyHealChange");
  lua_pushinteger(L,info->GetEvasionChange()); lua_setfield(L,-2,"EvasionChange");
  lua_pushinteger(L,info->GetExperiencePercent()); lua_setfield(L,-2,"ExperiencePercent");
  lua_pushinteger(L,info->GetExtraAttacks()); lua_setfield(L,-2,"ExtraAttacks");
  lua_pushinteger(L,info->GetExtraNavalMoves()); lua_setfield(L,-2,"ExtraNavalMovement");
  lua_pushinteger(L,info->GetExtraWithdrawal()); lua_setfield(L,-2,"ExtraWithdrawal");
  lua_pushinteger(L,info->GetFlankAttackModifier()); lua_setfield(L,-2,"FlankAttackModifier");
  lua_pushboolean(L,info->IsFlatMovementCost()); lua_setfield(L,-2,"FlatMovementCost");
  lua_pushboolean(L,info->IsFreePillageMoves()); lua_setfield(L,-2,"FreePillageMoves");
  lua_pushinteger(L,info->GetFriendlyHealChange()); lua_setfield(L,-2,"FriendlyHealChange");
  lua_pushinteger(L,info->GetFriendlyLandsModifier()); lua_setfield(L,-2,"FriendlyLandsModifier");
  lua_pushinteger(L,info->GetGoldenAgeValueFromKills()); lua_setfield(L,-2,"GoldenAgeValueFromKills");
  lua_pushboolean(L,info->IsGreatAdmiral()); lua_setfield(L,-2,"GreatAdmiral");
  lua_pushboolean(L,info->IsGreatGeneral()); lua_setfield(L,-2,"GreatGeneral");
  lua_pushinteger(L,info->GetGreatGeneralCombatModifier()); lua_setfield(L,-2,"GreatGeneralCombatModifier");
  lua_pushinteger(L,info->GetGreatGeneralModifier()); lua_setfield(L,-2,"GreatGeneralModifier");
  lua_pushboolean(L,info->IsGreatGeneralReceivesMovement()); lua_setfield(L,-2,"GreatGeneralReceivesMovement");
  lua_pushinteger(L,info->GetHPHealedIfDefeatEnemy()); lua_setfield(L,-2,"HPHealedIfDestroyEnemy");
  lua_pushboolean(L,info->HasPostCombatPromotions()); lua_setfield(L,-2,"HasPostCombatPromotions");
  lua_pushboolean(L,info->IsHealIfDefeatExcludeBarbarians()); lua_setfield(L,-2,"HealIfDestroyExcludesBarbarians");
  lua_pushboolean(L,info->IsHealOnPillage()); lua_setfield(L,-2,"HealOnPillage");
  lua_pushboolean(L,info->IsHealOutsideFriendly()); lua_setfield(L,-2,"HealOutsideFriendly");
  lua_pushboolean(L,info->IsCanHeavyCharge()); lua_setfield(L,-2,"HeavyCharge");
  lua_pushinteger(L,info->GetHeavyChargeDownhill()); lua_setfield(L,-2,"HeavyChargeDownhill");
  lua_pushinteger(L,info->GetHillsAttackPercent()); lua_setfield(L,-2,"HillsAttack");
  lua_pushinteger(L,info->GetHillsDefensePercent()); lua_setfield(L,-2,"HillsDefense");
  lua_pushboolean(L,info->IsHillsDoubleMove()); lua_setfield(L,-2,"HillsDoubleMove");
  lua_pushboolean(L,info->IsHoveringUnit()); lua_setfield(L,-2,"HoveringUnit");
  lua_pushboolean(L,info->IsIgnoreTerrainCost()); lua_setfield(L,-2,"IgnoreTerrainCost");
  lua_pushboolean(L,info->IsIgnoreZOC()); lua_setfield(L,-2,"IgnoreZOC");
  lua_pushboolean(L,info->IsInstaHeal()); lua_setfield(L,-2,"InstaHeal");
  lua_pushinteger(L,info->GetInterceptChanceChange()); lua_setfield(L,-2,"InterceptChanceChange");
  lua_pushinteger(L,info->GetInterceptionCombatModifier()); lua_setfield(L,-2,"InterceptionCombatModifier");
  lua_pushinteger(L,info->GetInterceptionDefenseDamageModifier()); lua_setfield(L,-2,"InterceptionDefenseDamageModifier");
  lua_pushboolean(L,info->IsKillRefreshMove()); lua_setfield(L,-2,"KillRefreshMove");
  lua_pushboolean(L,info->IsLandUnitReceivesMovement()); lua_setfield(L,-2,"LandUnitReceivesMovement");
  lua_pushboolean(L,info->IsLostWithUpgrade()); lua_setfield(L,-2,"LostWithUpgrade");
  lua_pushinteger(L,info->GetMovesChange()); lua_setfield(L,-2,"MovesChange");
  lua_pushboolean(L,info->IsMustSetUpToRangedAttack()); lua_setfield(L,-2,"MustSetUpToRangedAttack");
  lua_pushinteger(L,info->GetNearbyEnemyCombatMod()); lua_setfield(L,-2,"NearbyEnemyCombatMod");
  lua_pushinteger(L,info->GetNearbyEnemyCombatRange()); lua_setfield(L,-2,"NearbyEnemyCombatRange");
  lua_pushinteger(L,info->GetNearbyWaterCombatModifier()); lua_setfield(L,-2,"NearbyWaterCombatModifier");
  lua_pushinteger(L,info->GetNeutralHealChange()); lua_setfield(L,-2,"NeutralHealChange");
  lua_pushboolean(L,info->IsNoCapture()); lua_setfield(L,-2,"NoCapture");
  lua_pushboolean(L,info->IsNoDefensiveBonus()); lua_setfield(L,-2,"NoDefensiveBonus");
  lua_pushboolean(L,info->IsNukeImmune()); lua_setfield(L,-2,"NukeImmune");
  lua_pushinteger(L,info->GetNumInterceptionChange()); lua_setfield(L,-2,"NumInterceptionChange");
  lua_pushboolean(L,info->IsOnlyDefensive()); lua_setfield(L,-2,"OnlyDefensive");
  lua_pushinteger(L,info->GetOpenAttackPercent()); lua_setfield(L,-2,"OpenAttack");
  lua_pushinteger(L,info->GetOpenDefensePercent()); lua_setfield(L,-2,"OpenDefense");
  lua_pushinteger(L,info->GetOpenRangedAttackMod()); lua_setfield(L,-2,"OpenRangedAttackMod");
  lua_pushinteger(L,info->GetOutsideFriendlyLandsModifier()); lua_setfield(L,-2,"OutsideFriendlyLandsModifier");
  lua_pushinteger(L,info->GetPillageChange()); lua_setfield(L,-2,"PillageChange");
  lua_pushinteger(L,info->GetPillageHealChange()); lua_setfield(L,-2,"PillageHealChange");
  lua_pushinteger(L,info->GetPillageXPChange()); lua_setfield(L,-2,"PillageXPChange");
  lua_pushboolean(L,info->IsRangeAttackIgnoreLOS()); lua_setfield(L,-2,"RangeAttackIgnoreLOS");
  lua_pushinteger(L,info->GetRangeChange()); lua_setfield(L,-2,"RangeChange");
  lua_pushinteger(L,info->GetRangedAttackModifier()); lua_setfield(L,-2,"RangedAttackModifier");
  lua_pushinteger(L,info->GetRangedDefenseMod()); lua_setfield(L,-2,"RangedDefenseMod");
  lua_pushboolean(L,info->IsRangedSupportFire()); lua_setfield(L,-2,"RangedSupportFire");
  lua_pushboolean(L,info->IsRecon()); lua_setfield(L,-2,"Recon");
  lua_pushinteger(L,info->GetReligiousStrengthLossRivalTerritory()); lua_setfield(L,-2,"ReligiousStrengthLossRivalTerritory");
  lua_pushboolean(L,info->IsRivalTerritory()); lua_setfield(L,-2,"RivalTerritory");
  lua_pushboolean(L,info->IsRiver()); lua_setfield(L,-2,"River");
  lua_pushinteger(L,info->GetRoughAttackPercent()); lua_setfield(L,-2,"RoughAttack");
  lua_pushinteger(L,info->GetRoughDefensePercent()); lua_setfield(L,-2,"RoughDefense");
  lua_pushinteger(L,info->GetRoughRangedAttackMod()); lua_setfield(L,-2,"RoughRangedAttackMod");
  lua_pushboolean(L,info->IsRoughTerrainEndsTurn()); lua_setfield(L,-2,"RoughTerrainEndsTurn");
  lua_pushboolean(L,info->IsSapper()); lua_setfield(L,-2,"Sapper");
  lua_pushinteger(L,info->GetTradeMissionGoldModifier()); lua_setfield(L,-2,"TradeMissionGoldModifier");
  lua_pushinteger(L,info->GetTradeMissionInfluenceModifier()); lua_setfield(L,-2,"TradeMissionInfluenceModifier");
  lua_pushinteger(L,info->GetUpgradeDiscount()); lua_setfield(L,-2,"UpgradeDiscount");
  lua_pushinteger(L,info->GetVisibilityChange()); lua_setfield(L,-2,"VisibilityChange");
  return 1;
 }
 if (std::strcmp(table,"Traits") == 0)
 {
  if (id<0 || id>=static_cast<int>(GC.getNumTraitInfos())) return luaL_error(L,"info-cache index out of bounds");
  const CvTraitEntry* info=GC.getTraitInfo(static_cast<TraitTypes>(id));
  if (!info) return luaL_error(L,"info-cache entry missing");
  lua_createtable(L,0,77);
  lua_pushboolean(L,info->IsAbleToAnnexCityStates()); lua_setfield(L,-2,"AbleToAnnexCityStates");
  lua_pushinteger(L,info->GetAfraidMinorPerTurnInfluence()); lua_setfield(L,-2,"AfraidMinorPerTurnInfluence");
  lua_pushboolean(L,info->IsBonusReligiousBelief()); lua_setfield(L,-2,"BonusReligiousBelief");
  lua_pushinteger(L,info->GetCapitalBuildingModifier()); lua_setfield(L,-2,"CapitalBuildingModifier");
  lua_pushinteger(L,info->GetCapitalThemingBonusModifier()); lua_setfield(L,-2,"CapitalThemingBonusModifier");
  lua_pushinteger(L,info->GetCityConnectionTradeRouteChange()); lua_setfield(L,-2,"CityConnectionTradeRouteChange");
  lua_pushinteger(L,info->GetCityStateBonusModifier()); lua_setfield(L,-2,"CityStateBonusModifier");
  lua_pushinteger(L,info->GetCityStateCombatModifier()); lua_setfield(L,-2,"CityStateCombatModifier");
  lua_pushinteger(L,info->GetCityStateFriendshipModifier()); lua_setfield(L,-2,"CityStateFriendshipModifier");
  lua_pushinteger(L,info->GetCityStateUnitGiftExtraExperience()); lua_setfield(L,-2,"CityStateUnitGiftExtraExperience");
  lua_pushinteger(L,info->GetCityUnhappinessModifier()); lua_setfield(L,-2,"CityUnhappinessModifier");
  lua_pushboolean(L,info->IsCiviliansEmbarkOneMove()); lua_setfield(L,-2,"CiviliansEmbarkOneMove");
  lua_pushinteger(L,info->GetCombatBonusVsLargerCiv()); lua_setfield(L,-2,"CombatBonusVsLargerCiv");
  lua_pushboolean(L,info->IsCrossesMountainsAfterGreatGeneral()); lua_setfield(L,-2,"CrossesMountainsAfterGreatGeneral");
  lua_pushinteger(L,info->GetCultureFromKills()); lua_setfield(L,-2,"CultureFromKills");
  lua_pushboolean(L,info->IsEmbarkedAllWater()); lua_setfield(L,-2,"EmbarkedAllWater");
  lua_pushboolean(L,info->IsEmbarkedToLandFlatCost()); lua_setfield(L,-2,"EmbarkedToLandFlatCost");
  lua_pushboolean(L,info->IsEmbarkedUnitsFullStrength()); lua_setfield(L,-2,"EmbarkedUnitsFullStrength");
  lua_pushinteger(L,info->GetExtraEmbarkMoves()); lua_setfield(L,-2,"ExtraEmbarkMoves");
  lua_pushinteger(L,info->GetExtraFoundedCityTerritoryClaimRange()); lua_setfield(L,-2,"ExtraFoundedCityTerritoryClaimRange");
  lua_pushinteger(L,info->GetExtraHappinessPerLuxury()); lua_setfield(L,-2,"ExtraHappinessPerLuxury");
  lua_pushinteger(L,info->GetExtraSpies()); lua_setfield(L,-2,"ExtraSpies");
  lua_pushinteger(L,info->GetFaithCostModifier()); lua_setfield(L,-2,"FaithCostModifier");
  lua_pushboolean(L,info->IsFaithFromUnimprovedForest()); lua_setfield(L,-2,"FaithFromUnimprovedForest");
  lua_pushboolean(L,info->IsFasterAlongRiver()); lua_setfield(L,-2,"FasterAlongRiver");
  lua_pushboolean(L,info->IsFasterInHills()); lua_setfield(L,-2,"FasterInHills");
  lua_pushboolean(L,info->IsFightWellDamaged()); lua_setfield(L,-2,"FightWellDamaged");
  lua_pushinteger(L,info->GetFirstProphetCostMod()); lua_setfield(L,-2,"FirstProphetCostMod");
  lua_pushinteger(L,info->GetForeignRelgionPressureModifier()); lua_setfield(L,-2,"ForeignRelgionPressureModifier");
  lua_pushinteger(L,info->GetFriendlyLandsCitizenMoveChange()); lua_setfield(L,-2,"FriendlyLandsCitizenMoveChange");
  lua_pushinteger(L,info->GetGlobalHappinessPerCity()); lua_setfield(L,-2,"GlobalHappinessPerCity");
  lua_pushinteger(L,info->GetGoldenAgeDurationModifier()); lua_setfield(L,-2,"GoldenAgeDurationModifier");
  lua_pushinteger(L,info->GetGoldenAgeGreatArtistRateModifier()); lua_setfield(L,-2,"GoldenAgeGreatArtistRateModifier");
  lua_pushinteger(L,info->GetGoldenAgeGreatMusicianRateModifier()); lua_setfield(L,-2,"GoldenAgeGreatMusicianRateModifier");
  lua_pushinteger(L,info->GetGoldenAgeGreatWriterRateModifier()); lua_setfield(L,-2,"GoldenAgeGreatWriterRateModifier");
  lua_pushinteger(L,info->GetGoldenAgeMoveChange()); lua_setfield(L,-2,"GoldenAgeMoveChange");
  lua_pushinteger(L,info->GetGreatEngineerRateModifier()); lua_setfield(L,-2,"GreatEngineerRateModifier");
  lua_pushinteger(L,info->GetGreatGeneralExtraBonus()); lua_setfield(L,-2,"GreatGeneralExtraBonus");
  lua_pushinteger(L,info->GetGreatGeneralRateModifier()); lua_setfield(L,-2,"GreatGeneralRateModifier");
  lua_pushinteger(L,info->GetGreatGeneralSiegeBonus()); lua_setfield(L,-2,"GreatGeneralSiegeBonus");
  lua_pushinteger(L,info->GetGreatPeopleRateModifier()); lua_setfield(L,-2,"GreatPeopleRateModifier");
  lua_pushinteger(L,info->GetGreatPersonGiftInfluence()); lua_setfield(L,-2,"GreatPersonGiftInfluence");
  lua_pushinteger(L,info->GetGreatScientistRateModifier()); lua_setfield(L,-2,"GreatScientistRateModifier");
  lua_pushboolean(L,info->IsHalfMoreSpecialistUnhappiness()); lua_setfield(L,-2,"HalfMoreSpecialistUnhappiness");
  lua_pushinteger(L,info->GetHappinessPerReligion()); lua_setfield(L,-2,"HappinessPerReligion");
  lua_pushinteger(L,info->GetIdeologyPressureUnhappinessModifier()); lua_setfield(L,-2,"IdeologyPressureUnhappinessModifier");
  lua_pushinteger(L,info->GetImprovementMaintenanceModifier()); lua_setfield(L,-2,"ImprovementMaintenanceModifier");
  lua_pushinteger(L,info->GetLevelExperienceModifier()); lua_setfield(L,-2,"LevelExperienceModifier");
  lua_pushboolean(L,info->IsMayaCalendarBonuses()); lua_setfield(L,-2,"MayaCalendarBonuses");
  lua_pushinteger(L,info->GetMinorBullyModifier()); lua_setfield(L,-2,"MinorBullyModifier");
  lua_pushinteger(L,info->GetMinorFriendshipMinimum()); lua_setfield(L,-2,"MinorFriendshipMinimum");
  lua_pushboolean(L,info->IsMoveFriendlyWoodsAsRoad()); lua_setfield(L,-2,"MoveFriendlyWoodsAsRoad");
  lua_pushinteger(L,info->GetNaturalWonderFirstFinderFaith()); lua_setfield(L,-2,"NaturalWonderFirstFinderFaith");
  lua_pushinteger(L,info->GetNaturalWonderFirstFinderGold()); lua_setfield(L,-2,"NaturalWonderFirstFinderGold");
  lua_pushinteger(L,info->GetNaturalWonderHappinessModifier()); lua_setfield(L,-2,"NaturalWonderHappinessModifier");
  lua_pushinteger(L,info->GetNaturalWonderSubsequentFinderFaith()); lua_setfield(L,-2,"NaturalWonderSubsequentFinderFaith");
  lua_pushinteger(L,info->GetNaturalWonderSubsequentFinderGold()); lua_setfield(L,-2,"NaturalWonderSubsequentFinderGold");
  lua_pushinteger(L,info->GetNaturalWonderYieldModifier()); lua_setfield(L,-2,"NaturalWonderYieldModifier");
  lua_pushinteger(L,info->GetNavalUnitMaintenanceModifier()); lua_setfield(L,-2,"NavalUnitMaintenanceModifier");
  lua_pushinteger(L,info->GetNearbyImprovementBonusRange()); lua_setfield(L,-2,"NearbyImprovementBonusRange");
  lua_pushinteger(L,info->GetNearbyImprovementCombatBonus()); lua_setfield(L,-2,"NearbyImprovementCombatBonus");
  lua_pushboolean(L,info->IsNoAnnexing()); lua_setfield(L,-2,"NoAnnexing");
  lua_pushboolean(L,info->IsNoHillsImprovementMaintenance()); lua_setfield(L,-2,"NoHillsImprovementMaintenance");
  lua_pushinteger(L,info->GetNumTradeRoutesModifier()); lua_setfield(L,-2,"NumTradeRoutesModifier");
  lua_pushinteger(L,info->GetPlotBuyCostModifier()); lua_setfield(L,-2,"PlotBuyCostModifier");
  lua_pushinteger(L,info->GetPlotCultureCostModifier()); lua_setfield(L,-2,"PlotCultureCostModifier");
  lua_pushinteger(L,info->GetPlunderModifier()); lua_setfield(L,-2,"PlunderModifier");
  lua_pushinteger(L,info->GetPolicyCostModifier()); lua_setfield(L,-2,"PolicyCostModifier");
  lua_pushinteger(L,info->GetPopulationUnhappinessModifier()); lua_setfield(L,-2,"PopulationUnhappinessModifier");
  lua_pushinteger(L,info->GetRazeSpeedModifier()); lua_setfield(L,-2,"RazeSpeedModifier");
  lua_pushboolean(L,info->IsReligionEnhanceReformation()); lua_setfield(L,-2,"ReligionEnhanceReformation");
  lua_pushboolean(L,info->IsSeaTradeRoutesArePlunderImmune()); lua_setfield(L,-2,"SeaTradeRoutesArePlunderImmune");
  lua_pushinteger(L,info->GetSelfReligiousPressureModifier()); lua_setfield(L,-2,"SelfReligiousPressureModifier");
  lua_pushinteger(L,info->GetTradeRouteResourceModifier()); lua_setfield(L,-2,"TradeRouteResourceModifier");
  lua_pushinteger(L,info->GetUnhappinessModifierForPuppetedCities()); lua_setfield(L,-2,"UnhappinessModifierForPuppetedCities");
  lua_pushinteger(L,info->GetWonderProductionModifier()); lua_setfield(L,-2,"WonderProductionModifier");
  lua_pushinteger(L,info->GetWorkerSpeedModifier()); lua_setfield(L,-2,"WorkerSpeedModifier");
  return 1;
 }
 if (std::strcmp(table,"Policies") == 0)
 {
  if (id<0 || id>=static_cast<int>(GC.getNumPolicyInfos())) return luaL_error(L,"info-cache index out of bounds");
  const CvPolicyEntry* info=GC.getPolicyInfo(static_cast<PolicyTypes>(id));
  if (!info) return luaL_error(L,"info-cache entry missing");
  lua_createtable(L,0,93);
  lua_pushboolean(L,info->IsAddReformationBelief()); lua_setfield(L,-2,"AddReformationBelief");
  lua_pushboolean(L,info->IsAlwaysSeeBarbCamps()); lua_setfield(L,-2,"AlwaysSeeBarbCamps");
  lua_pushinteger(L,info->GetAttackBonusTurns()); lua_setfield(L,-2,"AttackBonusTurns");
  lua_pushinteger(L,info->GetBarbarianCombatBonus()); lua_setfield(L,-2,"BarbarianCombatBonus");
  lua_pushinteger(L,info->GetBaseFreeUnits()); lua_setfield(L,-2,"BaseFreeUnits");
  lua_pushinteger(L,info->GetBuildingGoldMaintenanceMod()); lua_setfield(L,-2,"BuildingGoldMaintenanceMod");
  lua_pushinteger(L,info->GetBuildingProductionModifier()); lua_setfield(L,-2,"BuildingProductionModifier");
  lua_pushinteger(L,info->GetBuildingPurchaseCostModifier()); lua_setfield(L,-2,"BuildingPurchaseCostModifier");
  lua_pushinteger(L,info->GetCapitalGrowthMod()); lua_setfield(L,-2,"CapitalGrowthMod");
  lua_pushinteger(L,info->GetCapitalSettlerProductionModifier()); lua_setfield(L,-2,"CapitalSettlerProductionModifier");
  lua_pushinteger(L,info->GetCapitalUnhappinessMod()); lua_setfield(L,-2,"CapitalUnhappinessMod");
  lua_pushinteger(L,info->GetCatchSpiesModifier()); lua_setfield(L,-2,"CatchSpiesModifier");
  lua_pushinteger(L,info->GetCityConnectionTradeRouteGoldModifier()); lua_setfield(L,-2,"CityConnectionTradeRouteGoldModifier");
  lua_pushinteger(L,info->GetCityGrowthMod()); lua_setfield(L,-2,"CityGrowthMod");
  lua_pushinteger(L,info->GetCityStateBonusModifier()); lua_setfield(L,-2,"CityStateBonusModifier");
  lua_pushinteger(L,info->GetCityStateUnitFrequencyModifier()); lua_setfield(L,-2,"CityStateUnitFrequencyModifier");
  lua_pushinteger(L,info->GetCityStrengthMod()); lua_setfield(L,-2,"CityStrengthMod");
  lua_pushinteger(L,info->GetCommonFoeTourismModifier()); lua_setfield(L,-2,"CommonFoeTourismModifier");
  lua_pushinteger(L,info->GetCultureCost()); lua_setfield(L,-2,"CultureCost");
  lua_pushinteger(L,info->GetCultureFromKills()); lua_setfield(L,-2,"CultureFromKills");
  lua_pushinteger(L,info->GetCulturePerCity()); lua_setfield(L,-2,"CulturePerCity");
  lua_pushinteger(L,info->GetCulturePerGarrisonedUnit()); lua_setfield(L,-2,"CulturePerGarrisonedUnit");
  lua_pushboolean(L,info->IsEnablesSSPartHurry()); lua_setfield(L,-2,"EnablesSSPartHurry");
  lua_pushboolean(L,info->IsEnablesSSPartPurchase()); lua_setfield(L,-2,"EnablesSSPartPurchase");
  lua_pushinteger(L,info->GetExpInBorderModifier()); lua_setfield(L,-2,"ExpInBorderModifier");
  lua_pushinteger(L,info->GetExpModifier()); lua_setfield(L,-2,"ExpModifier");
  lua_pushinteger(L,info->GetExtraHappiness()); lua_setfield(L,-2,"ExtraHappiness");
  lua_pushinteger(L,info->GetExtraHappinessPerLuxury()); lua_setfield(L,-2,"ExtraHappinessPerLuxury");
  lua_pushinteger(L,info->GetExtraTerritoryClaim()); lua_setfield(L,-2,"ExtraTerritoryClaim");
  lua_pushinteger(L,info->GetFaithCostModifier()); lua_setfield(L,-2,"FaithCostModifier");
  lua_pushinteger(L,info->GetFreeExperience()); lua_setfield(L,-2,"FreeExperience");
  lua_pushboolean(L,info->IsGarrisonFreeMaintenance()); lua_setfield(L,-2,"GarrisonFreeMaintenance");
  lua_pushinteger(L,info->GetGarrisonedCityRangeStrikeModifier()); lua_setfield(L,-2,"GarrisonedCityRangeStrikeModifier");
  lua_pushinteger(L,info->GetGlobalMoveChangeFriendly()); lua_setfield(L,-2,"GlobalMoveChangeFriendly");
  lua_pushinteger(L,info->GetGoldFromKills()); lua_setfield(L,-2,"GoldFromKills");
  lua_pushinteger(L,info->GetGoldenAgeDurationMod()); lua_setfield(L,-2,"GoldenAgeDurationMod");
  lua_pushinteger(L,info->GetGoldenAgeTurns()); lua_setfield(L,-2,"GoldenAgeTurns");
  lua_pushinteger(L,info->GetGreatAdmiralRateModifier()); lua_setfield(L,-2,"GreatAdmiralRateModifier");
  lua_pushinteger(L,info->GetGreatArtistRateModifier()); lua_setfield(L,-2,"GreatArtistRateModifier");
  lua_pushinteger(L,info->GetGreatMerchantRateModifier()); lua_setfield(L,-2,"GreatMerchantRateModifier");
  lua_pushinteger(L,info->GetGreatMusicianRateModifier()); lua_setfield(L,-2,"GreatMusicianRateModifier");
  lua_pushinteger(L,info->GetGreatPeopleRateModifier()); lua_setfield(L,-2,"GreatPeopleRateModifier");
  lua_pushinteger(L,info->GetGreatScientistRateModifier()); lua_setfield(L,-2,"GreatScientistRateModifier");
  lua_pushinteger(L,info->GetGreatWriterRateModifier()); lua_setfield(L,-2,"GreatWriterRateModifier");
  lua_pushboolean(L,info->IsHalfSpecialistFood()); lua_setfield(L,-2,"HalfSpecialistFood");
  lua_pushboolean(L,info->IsHalfSpecialistUnhappiness()); lua_setfield(L,-2,"HalfSpecialistUnhappiness");
  lua_pushinteger(L,info->GetHappinessPerGarrisonedUnit()); lua_setfield(L,-2,"HappinessPerGarrisonedUnit");
  lua_pushinteger(L,info->GetHappinessPerTradeRoute()); lua_setfield(L,-2,"HappinessPerTradeRoute");
  lua_pushinteger(L,info->GetHappinessPerXPopulation()); lua_setfield(L,-2,"HappinessPerXPopulation");
  lua_pushinteger(L,info->GetHappinessToScience()); lua_setfield(L,-2,"HappinessToScience");
  lua_pushinteger(L,info->GetIdeologyPressureUnhappinessModifier()); lua_setfield(L,-2,"IdeologyPressureUnhappinessModifier");
  lua_pushboolean(L,info->IncludesOneShotFreeUnits()); lua_setfield(L,-2,"IncludesOneShotFreeUnits");
  lua_pushinteger(L,info->GetInternalTradeRouteGoldChange()); lua_setfield(L,-2,"InternalTradeRouteGoldChange");
  lua_pushinteger(L,info->GetInternalTradeRouteYieldModifier()); lua_setfield(L,-2,"InternalTradeRouteYieldModifier");
  lua_pushinteger(L,info->GetLessHappyTourismModifier()); lua_setfield(L,-2,"LessHappyTourismModifier");
  lua_pushinteger(L,info->GetLevel()); lua_setfield(L,-2,"Level");
  lua_pushinteger(L,info->GetMilitaryProductionModifier()); lua_setfield(L,-2,"MilitaryProductionModifier");
  lua_pushinteger(L,info->GetMinorBullyInfluenceReward()); lua_setfield(L,-2,"MinorBullyInfluenceReward");
  lua_pushinteger(L,info->GetMinorBullyScoreModifier()); lua_setfield(L,-2,"MinorBullyScoreModifier");
  lua_pushinteger(L,info->GetMinorFriendshipDecayMod()); lua_setfield(L,-2,"MinorFriendshipDecayMod");
  lua_pushinteger(L,info->GetMinorFriendshipMinimum()); lua_setfield(L,-2,"MinorFriendshipMinimum");
  lua_pushinteger(L,info->GetMinorGoldFriendshipMod()); lua_setfield(L,-2,"MinorGoldFriendshipMod");
  lua_pushboolean(L,info->IsMinorGreatPeopleAllies()); lua_setfield(L,-2,"MinorGreatPeopleAllies");
  lua_pushinteger(L,info->GetMinorMilitaryNumExtraUnitsToGift()); lua_setfield(L,-2,"MinorMilitaryNumExtraUnitsToGift");
  lua_pushboolean(L,info->IsMinorResourceBonus()); lua_setfield(L,-2,"MinorResourceBonus");
  lua_pushboolean(L,info->IsMinorScienceAllies()); lua_setfield(L,-2,"MinorScienceAllies");
  lua_pushinteger(L,info->GetNewCityExtraPopulation()); lua_setfield(L,-2,"NewCityExtraPopulation");
  lua_pushinteger(L,info->GetNumCitiesFreeAestheticsSchools()); lua_setfield(L,-2,"NumCitiesFreeAestheticsSchools");
  lua_pushinteger(L,info->GetNumCitiesFreeCultureBuilding()); lua_setfield(L,-2,"NumCitiesFreeCultureBuilding");
  lua_pushinteger(L,info->GetNumCitiesFreeFoodBuilding()); lua_setfield(L,-2,"NumCitiesFreeFoodBuilding");
  lua_pushinteger(L,info->GetNumCitiesFreePietyGardens()); lua_setfield(L,-2,"NumCitiesFreePietyGardens");
  lua_pushinteger(L,info->GetNumCitiesPolicyCostDiscount()); lua_setfield(L,-2,"NumCitiesPolicyCostDiscount");
  lua_pushinteger(L,info->GetNumExtraLeagueVotes()); lua_setfield(L,-2,"NumExtraLeagueVotes");
  lua_pushinteger(L,info->GetNumExtraSpies()); lua_setfield(L,-2,"NumExtraSpies");
  lua_pushinteger(L,info->GetNumFreeGreatPeople()); lua_setfield(L,-2,"NumFreeGreatPeople");
  lua_pushinteger(L,info->GetNumFreePolicies()); lua_setfield(L,-2,"NumFreePolicies");
  lua_pushinteger(L,info->GetNumTradeRouteBonus()); lua_setfield(L,-2,"NumTradeRouteBonus");
  lua_pushboolean(L,info->IsOneShot()); lua_setfield(L,-2,"OneShot");
  lua_pushinteger(L,info->GetPlotCultureExponentModifier()); lua_setfield(L,-2,"PlotCultureExponentModifier");
  lua_pushinteger(L,info->GetProtectedMinorPerTurnInfluence()); lua_setfield(L,-2,"ProtectedMinorPerTurnInfluence");
  lua_pushinteger(L,info->GetRiggingElectionModifier()); lua_setfield(L,-2,"RiggingElectionModifier");
  lua_pushinteger(L,info->GetRouteGoldMaintenanceMod()); lua_setfield(L,-2,"RouteGoldMaintenanceMod");
  lua_pushinteger(L,info->GetScienceFromKills()); lua_setfield(L,-2,"ScienceFromKills");
  lua_pushboolean(L,info->IsSecondReligionPantheon()); lua_setfield(L,-2,"SecondReligionPantheon");
  lua_pushinteger(L,info->GetStealTechFasterModifier()); lua_setfield(L,-2,"StealTechFasterModifier");
  lua_pushinteger(L,info->GetStrategicResourceMod()); lua_setfield(L,-2,"StrategicResourceMod");
  lua_pushinteger(L,info->GetThemingBonusMultiplier()); lua_setfield(L,-2,"ThemingBonusMultiplier");
  lua_pushinteger(L,info->GetTradeMissionGoldModifier()); lua_setfield(L,-2,"TradeMissionGoldModifier");
  lua_pushinteger(L,info->GetUnhappinessMod()); lua_setfield(L,-2,"UnhappinessMod");
  lua_pushinteger(L,info->GetUnitGoldMaintenanceMod()); lua_setfield(L,-2,"UnitGoldMaintenanceMod");
  lua_pushinteger(L,info->GetUnitPurchaseCostModifier()); lua_setfield(L,-2,"UnitPurchaseCostModifier");
  lua_pushinteger(L,info->GetWonderProductionModifier()); lua_setfield(L,-2,"WonderProductionModifier");
  lua_pushinteger(L,info->GetWorkerSpeedModifier()); lua_setfield(L,-2,"WorkerSpeedModifier");
  return 1;
 }
 if (std::strcmp(table,"Beliefs") == 0)
 {
  if (id<0 || id>=static_cast<int>(GC.getNumBeliefInfos())) return luaL_error(L,"info-cache index out of bounds");
  const CvBeliefEntry* info=GC.getBeliefInfo(static_cast<BeliefTypes>(id));
  if (!info) return luaL_error(L,"info-cache entry missing");
  lua_createtable(L,0,29);
  lua_pushinteger(L,info->GetCityGrowthModifier()); lua_setfield(L,-2,"CityGrowthModifier");
  lua_pushinteger(L,info->GetCityRangeStrikeModifier()); lua_setfield(L,-2,"CityRangeStrikeModifier");
  lua_pushinteger(L,info->GetCityStateFollowingReligionDecayMod()); lua_setfield(L,-2,"CityStateFollowingReligionDecayMod");
  lua_pushinteger(L,info->GetCityStateFollowingReligionRecoveryMod()); lua_setfield(L,-2,"CityStateFollowingReligionRecoveryMod");
  lua_pushinteger(L,info->GetCityStateMinimumInfluence()); lua_setfield(L,-2,"CityStateMinimumInfluence");
  lua_pushinteger(L,info->GetCombatModifierEnemyCities()); lua_setfield(L,-2,"CombatModifierEnemyCities");
  lua_pushinteger(L,info->GetCombatModifierFriendlyCities()); lua_setfield(L,-2,"CombatModifierFriendlyCities");
  lua_pushboolean(L,info->IsEnhancerBelief()); lua_setfield(L,-2,"Enhancer");
  lua_pushinteger(L,info->GetExtraTradeRoutes()); lua_setfield(L,-2,"ExtraTradeRoutes");
  lua_pushboolean(L,info->IsFollowerBelief()); lua_setfield(L,-2,"Follower");
  lua_pushboolean(L,info->IsFounderBelief()); lua_setfield(L,-2,"Founder");
  lua_pushinteger(L,info->GetFriendlyCityStateSpreadModifier()); lua_setfield(L,-2,"FriendlyCityStateSpreadModifier");
  lua_pushinteger(L,info->GetGoldWhenCityAdopts()); lua_setfield(L,-2,"GoldPerFirstCityConversion");
  lua_pushinteger(L,info->GetGreatPersonExpendedFaith()); lua_setfield(L,-2,"GreatPersonExpendedFaith");
  lua_pushinteger(L,info->GetHappinessPerCity()); lua_setfield(L,-2,"HappinessPerCity");
  lua_pushnumber(L,info->GetHappinessPerFollowingCity()); lua_setfield(L,-2,"HappinessPerFollowingCity");
  lua_pushinteger(L,info->GetInquisitorPressureRetention()); lua_setfield(L,-2,"InquisitorPressureRetention");
  lua_pushinteger(L,info->GetMinPopulation()); lua_setfield(L,-2,"MinPopulation");
  lua_pushinteger(L,info->GetMissionaryCostModifier()); lua_setfield(L,-2,"MissionaryCostModifier");
  lua_pushinteger(L,info->GetMissionaryExtraSpreads()); lua_setfield(L,-2,"MissionaryExtraSpreads");
  lua_pushinteger(L,info->GetNumFreeSettlers()); lua_setfield(L,-2,"NumFreeSettlers");
  lua_pushboolean(L,info->IsPantheonBelief()); lua_setfield(L,-2,"Pantheon");
  lua_pushinteger(L,info->GetPlotCultureCostModifier()); lua_setfield(L,-2,"PlotCultureCostModifier");
  lua_pushinteger(L,info->GetProphetCostModifier()); lua_setfield(L,-2,"ProphetCostModifier");
  lua_pushinteger(L,info->GetProphetStrengthModifier()); lua_setfield(L,-2,"ProphetStrengthModifier");
  lua_pushboolean(L,info->IsReformationBelief()); lua_setfield(L,-2,"Reformation");
  lua_pushinteger(L,info->GetRiverHappiness()); lua_setfield(L,-2,"RiverHappiness");
  lua_pushinteger(L,info->GetSpreadModifierOwnedCities()); lua_setfield(L,-2,"SpreadModifierOwnedCities");
  lua_pushinteger(L,info->GetWonderProductionModifier()); lua_setfield(L,-2,"WonderProductionModifier");
  return 1;
 }
 if (std::strcmp(table,"Improvements") == 0)
 {
  if (id<0 || id>=static_cast<int>(GC.getNumImprovementInfos())) return luaL_error(L,"info-cache index out of bounds");
  const CvImprovementEntry* info=GC.getImprovementInfo(static_cast<ImprovementTypes>(id));
  if (!info) return luaL_error(L,"info-cache entry missing");
  lua_createtable(L,0,39);
  lua_pushboolean(L,info->IsActsAsRoute()); lua_setfield(L,-2,"ActsAsRoute");
  lua_pushboolean(L,info->IsAdjacentCityMakesValid()); lua_setfield(L,-2,"AdjacentCityMakesValid");
  lua_pushboolean(L,info->IsAdjacentLuxury()); lua_setfield(L,-2,"AdjacentLuxury");
  lua_pushboolean(L,info->IsAllowsSailLand()); lua_setfield(L,-2,"AllowsSailLand");
  lua_pushboolean(L,info->IsAllowsWalkWater()); lua_setfield(L,-2,"AllowsWalkWater");
  lua_pushboolean(L,info->IsBarbarianCamp()); lua_setfield(L,-2,"BarbarianCamp");
  lua_pushboolean(L,info->IsBuildableOnResources()); lua_setfield(L,-2,"BuildableOnResources");
  lua_pushboolean(L,info->IsCoastal()); lua_setfield(L,-2,"Coastal");
  lua_pushboolean(L,info->IsCreatedByGreatPerson()); lua_setfield(L,-2,"CreatedByGreatPerson");
  lua_pushinteger(L,info->GetCultureAdjacentSameType()); lua_setfield(L,-2,"CultureAdjacentSameType");
  lua_pushinteger(L,info->GetCultureBombRadius()); lua_setfield(L,-2,"CultureBombRadius");
  lua_pushinteger(L,info->GetDefenseModifier()); lua_setfield(L,-2,"DefenseModifier");
  lua_pushinteger(L,info->GetDefenseModifierGlobal()); lua_setfield(L,-2,"DefenseModifierGlobal");
  lua_pushboolean(L,info->IsDestroyedWhenPillaged()); lua_setfield(L,-2,"DestroyedWhenPillaged");
  lua_pushboolean(L,info->IsDisplacePillager()); lua_setfield(L,-2,"DisplacePillager");
  lua_pushboolean(L,info->IsFreshWaterMakesValid()); lua_setfield(L,-2,"FreshWaterMakesValid");
  lua_pushboolean(L,info->IsFreshWaterSource()); lua_setfield(L,-2,"FreshWaterSource");
  lua_pushboolean(L,info->IsGoody()); lua_setfield(L,-2,"Goody");
  lua_pushinteger(L,info->GetGoodyUniqueRange()); lua_setfield(L,-2,"GoodyRange");
  lua_pushboolean(L,info->IsHillsMakesValid()); lua_setfield(L,-2,"HillsMakesValid");
  lua_pushboolean(L,info->IsIgnoreOwnership()); lua_setfield(L,-2,"IgnoreOwnership");
  lua_pushboolean(L,info->IsInAdjacentFriendly()); lua_setfield(L,-2,"InAdjacentFriendly");
  lua_pushinteger(L,info->GetNearbyEnemyDamage()); lua_setfield(L,-2,"NearbyEnemyDamage");
  lua_pushboolean(L,info->IsNoTwoAdjacent()); lua_setfield(L,-2,"NoTwoAdjacent");
  lua_pushboolean(L,info->IsOutsideBorders()); lua_setfield(L,-2,"OutsideBorders");
  lua_pushboolean(L,info->IsPermanent()); lua_setfield(L,-2,"Permanent");
  lua_pushinteger(L,info->GetPillageGold()); lua_setfield(L,-2,"PillageGold");
  lua_pushboolean(L,info->IsPromptWhenComplete()); lua_setfield(L,-2,"PromptWhenComplete");
  lua_pushboolean(L,info->IsRemovesResource()); lua_setfield(L,-2,"RemovesResource");
  lua_pushboolean(L,info->IsRequiresFeature()); lua_setfield(L,-2,"RequiresFeature");
  lua_pushboolean(L,info->IsRequiresFlatlands()); lua_setfield(L,-2,"RequiresFlatlands");
  lua_pushboolean(L,info->IsRequiresFlatlandsOrFreshWater()); lua_setfield(L,-2,"RequiresFlatlandsOrFreshWater");
  lua_pushboolean(L,info->IsRequiresImprovement()); lua_setfield(L,-2,"RequiresImprovement");
  lua_pushinteger(L,info->GetRequiresXAdjacentLand()); lua_setfield(L,-2,"RequiresXAdjacentLand");
  lua_pushboolean(L,info->IsSpecificCivRequired()); lua_setfield(L,-2,"SpecificCivRequired");
  lua_pushinteger(L,info->GetStackedDomainDefensePenalty()); lua_setfield(L,-2,"StackedDomainDefensePenalty");
  lua_pushinteger(L,info->GetTilesPerGoody()); lua_setfield(L,-2,"TilesPerGoody");
  lua_pushboolean(L,info->IsWater()); lua_setfield(L,-2,"Water");
  lua_pushboolean(L,info->IsWaterAdjacencyMakesValid()); lua_setfield(L,-2,"WaterAdjacencyMakesValid");
  return 1;
 }
 if (std::strcmp(table,"Technologies") == 0)
 {
  if (id<0 || id>=static_cast<int>(GC.getNumTechInfos())) return luaL_error(L,"info-cache index out of bounds");
  const CvTechEntry* info=GC.getTechInfo(static_cast<TechTypes>(id));
  if (!info) return luaL_error(L,"info-cache entry missing");
  lua_createtable(L,0,20);
  lua_pushinteger(L,info->GetExtraLeagueVotes()); lua_setfield(L,-2,"AdditionalDelegates");
  lua_pushinteger(L,info->GetAdvancedStartCost()); lua_setfield(L,-2,"AdvancedStartCost");
  lua_pushboolean(L,info->IsAllowEmbassyTradingAllowed()); lua_setfield(L,-2,"AllowEmbassyTradingAllowed");
  lua_pushboolean(L,info->IsAllowsEmbarking()); lua_setfield(L,-2,"AllowsEmbarking");
  lua_pushboolean(L,info->IsAllowsWorldCongress()); lua_setfield(L,-2,"AllowsWorldCongress");
  lua_pushboolean(L,info->IsBridgeBuilding()); lua_setfield(L,-2,"BridgeBuilding");
  lua_pushinteger(L,info->GetResearchCost()); lua_setfield(L,-2,"Cost");
  lua_pushboolean(L,info->IsDefensivePactTradingAllowed()); lua_setfield(L,-2,"DefensivePactTradingAllowed");
  lua_pushboolean(L,info->IsEmbarkedAllWaterPassage()); lua_setfield(L,-2,"EmbarkedAllWaterPassage");
  lua_pushinteger(L,info->GetEmbarkedMoveChange()); lua_setfield(L,-2,"EmbarkedMoveChange");
  lua_pushinteger(L,info->GetEmbarkedSightChange()); lua_setfield(L,-2,"EmbarkedSightChange");
  lua_pushinteger(L,info->GetExtraVotesPerDiplomat()); lua_setfield(L,-2,"ExtraVotesPerDiplomat");
  lua_pushboolean(L,info->IsGoodyTech()); lua_setfield(L,-2,"GoodyTech");
  lua_pushinteger(L,info->GetInfluenceSpreadModifier()); lua_setfield(L,-2,"InfluenceSpreadModifier");
  lua_pushinteger(L,info->GetNumInternationalTradeRoutesChange()); lua_setfield(L,-2,"InternationalTradeRoutesChange");
  lua_pushboolean(L,info->IsMapVisible()); lua_setfield(L,-2,"MapVisible");
  lua_pushboolean(L,info->IsOpenBordersTradingAllowed()); lua_setfield(L,-2,"OpenBordersTradingAllowed");
  lua_pushboolean(L,info->IsRepeat()); lua_setfield(L,-2,"Repeat");
  lua_pushboolean(L,info->IsTrade()); lua_setfield(L,-2,"Trade");
  lua_pushboolean(L,info->IsTriggersArchaeologicalSites()); lua_setfield(L,-2,"TriggersArchaeologicalSites");
  return 1;
 }
 if (std::strcmp(table,"Projects") == 0)
 {
  if (id<0 || id>=static_cast<int>(GC.getNumProjectInfos())) return luaL_error(L,"info-cache index out of bounds");
  const CvProjectEntry* info=GC.getProjectInfo(static_cast<ProjectTypes>(id));
  if (!info) return luaL_error(L,"info-cache entry missing");
  lua_createtable(L,0,5);
  lua_pushboolean(L,info->IsAllowsNukes()); lua_setfield(L,-2,"AllowsNukes");
  lua_pushinteger(L,info->GetProductionCost()); lua_setfield(L,-2,"Cost");
  lua_pushinteger(L,info->GetMaxGlobalInstances()); lua_setfield(L,-2,"MaxGlobalInstances");
  lua_pushinteger(L,info->GetMaxTeamInstances()); lua_setfield(L,-2,"MaxTeamInstances");
  lua_pushboolean(L,info->IsSpaceship()); lua_setfield(L,-2,"Spaceship");
  return 1;
 }
 if (std::strcmp(table,"Specialists") == 0)
 {
  if (id<0 || id>=static_cast<int>(GC.getNumSpecialistInfos())) return luaL_error(L,"info-cache index out of bounds");
  const CvSpecialistInfo* info=GC.getSpecialistInfo(static_cast<SpecialistTypes>(id));
  if (!info) return luaL_error(L,"info-cache entry missing");
  lua_createtable(L,0,2);
  lua_pushinteger(L,info->getGreatPeopleRateChange()); lua_setfield(L,-2,"GreatPeopleRateChange");
  lua_pushboolean(L,info->isVisible()); lua_setfield(L,-2,"Visible");
  return 1;
 }
 if (std::strcmp(table,"HandicapInfos") == 0)
 {
  if (id<0 || id>=static_cast<int>(GC.getNumHandicapInfos())) return luaL_error(L,"info-cache index out of bounds");
  const CvHandicapInfo* info=GC.getHandicapInfo(static_cast<HandicapTypes>(id));
  if (!info) return luaL_error(L,"info-cache entry missing");
  lua_createtable(L,0,50);
  lua_pushinteger(L,info->getAIAdvancedStartPercent()); lua_setfield(L,-2,"AIAdvancedStartPercent");
  lua_pushinteger(L,info->getAIBarbarianCombatModifier()); lua_setfield(L,-2,"AIBarbarianBonus");
  lua_pushinteger(L,info->getAIBuildingCostPercent()); lua_setfield(L,-2,"AIBuildingCostPercent");
  lua_pushinteger(L,info->getAIConstructPercent()); lua_setfield(L,-2,"AIConstructPercent");
  lua_pushinteger(L,info->getAICreatePercent()); lua_setfield(L,-2,"AICreatePercent");
  lua_pushinteger(L,info->getAIDeclareWarProb()); lua_setfield(L,-2,"AIDeclareWarProb");
  lua_pushinteger(L,info->getAIFreeXP()); lua_setfield(L,-2,"AIFreeXP");
  lua_pushinteger(L,info->getAIFreeXPPercent()); lua_setfield(L,-2,"AIFreeXPPercent");
  lua_pushinteger(L,info->getAIGrowthPercent()); lua_setfield(L,-2,"AIGrowthPercent");
  lua_pushinteger(L,info->getAIPerEraModifier()); lua_setfield(L,-2,"AIPerEraModifier");
  lua_pushinteger(L,info->getAIStartingDefenseUnits()); lua_setfield(L,-2,"AIStartingDefenseUnits");
  lua_pushinteger(L,info->getAIStartingExploreUnits()); lua_setfield(L,-2,"AIStartingExploreUnits");
  lua_pushinteger(L,info->getAIStartingUnitMultiplier()); lua_setfield(L,-2,"AIStartingUnitMultiplier");
  lua_pushinteger(L,info->getAIStartingWorkerUnits()); lua_setfield(L,-2,"AIStartingWorkerUnits");
  lua_pushinteger(L,info->getAITrainPercent()); lua_setfield(L,-2,"AITrainPercent");
  lua_pushinteger(L,info->getAIUnhappinessPercent()); lua_setfield(L,-2,"AIUnhappinessPercent");
  lua_pushinteger(L,info->getAIUnitCostPercent()); lua_setfield(L,-2,"AIUnitCostPercent");
  lua_pushinteger(L,info->getAIUnitSupplyPercent()); lua_setfield(L,-2,"AIUnitSupplyPercent");
  lua_pushinteger(L,info->getAIUnitUpgradePercent()); lua_setfield(L,-2,"AIUnitUpgradePercent");
  lua_pushinteger(L,info->getAIWorkRateModifier()); lua_setfield(L,-2,"AIWorkRateModifier");
  lua_pushinteger(L,info->getAIWorldConstructPercent()); lua_setfield(L,-2,"AIWorldConstructPercent");
  lua_pushinteger(L,info->getAIWorldCreatePercent()); lua_setfield(L,-2,"AIWorldCreatePercent");
  lua_pushinteger(L,info->getAIWorldTrainPercent()); lua_setfield(L,-2,"AIWorldTrainPercent");
  lua_pushinteger(L,info->getAdvancedStartPointsMod()); lua_setfield(L,-2,"AdvancedStartPointsMod");
  lua_pushinteger(L,info->getAttitudeChange()); lua_setfield(L,-2,"AttitudeChange");
  lua_pushinteger(L,info->getBarbCampGold()); lua_setfield(L,-2,"BarbCampGold");
  lua_pushinteger(L,info->getBarbSpawnMod()); lua_setfield(L,-2,"BarbSpawnMod");
  lua_pushinteger(L,info->getBarbarianCombatModifier()); lua_setfield(L,-2,"BarbarianBonus");
  lua_pushinteger(L,info->getBarbarianLandTargetRange()); lua_setfield(L,-2,"BarbarianLandTargetRange");
  lua_pushinteger(L,info->getBarbarianSeaTargetRange()); lua_setfield(L,-2,"BarbarianSeaTargetRange");
  lua_pushinteger(L,info->getBuildingCostPercent()); lua_setfield(L,-2,"BuildingCostPercent");
  lua_pushinteger(L,info->GetCityProductionNumOptions()); lua_setfield(L,-2,"CityProductionNumOptionsConsidered");
  lua_pushinteger(L,info->getEarliestBarbarianReleaseTurn()); lua_setfield(L,-2,"EarliestBarbarianReleaseTurn");
  lua_pushinteger(L,info->getExtraHappinessPerLuxury()); lua_setfield(L,-2,"ExtraHappinessPerLuxury");
  lua_pushinteger(L,info->getHappinessDefault()); lua_setfield(L,-2,"HappinessDefault");
  lua_pushinteger(L,info->getImprovementCostPercent()); lua_setfield(L,-2,"ImprovementCostPercent");
  lua_pushinteger(L,info->getNoTechTradeModifier()); lua_setfield(L,-2,"NoTechTradeModifier");
  lua_pushinteger(L,info->getNumCitiesUnhappinessMod()); lua_setfield(L,-2,"NumCitiesUnhappinessMod");
  lua_pushinteger(L,info->GetPolicyNumOptions()); lua_setfield(L,-2,"PolicyNumOptionsConsidered");
  lua_pushinteger(L,info->getPolicyPercent()); lua_setfield(L,-2,"PolicyPercent");
  lua_pushinteger(L,info->getPopulationUnhappinessMod()); lua_setfield(L,-2,"PopulationUnhappinessMod");
  lua_pushinteger(L,info->getProductionFreeUnits()); lua_setfield(L,-2,"ProductionFreeUnits");
  lua_pushinteger(L,info->getProductionFreeUnitsPerCity()); lua_setfield(L,-2,"ProductionFreeUnitsPerCity");
  lua_pushinteger(L,info->getProductionFreeUnitsPopulationPercent()); lua_setfield(L,-2,"ProductionFreeUnitsPopulationPercent");
  lua_pushinteger(L,info->getResearchPercent()); lua_setfield(L,-2,"ResearchPercent");
  lua_pushinteger(L,info->getRouteCostPercent()); lua_setfield(L,-2,"RouteCostPercent");
  lua_pushinteger(L,info->getStartingLocationPercent()); lua_setfield(L,-2,"StartingLocPercent");
  lua_pushinteger(L,info->GetTechNumOptions()); lua_setfield(L,-2,"TechNumOptionsConsidered");
  lua_pushinteger(L,info->getTechTradeKnownModifier()); lua_setfield(L,-2,"TechTradeKnownModifier");
  lua_pushinteger(L,info->getUnitCostPercent()); lua_setfield(L,-2,"UnitCostPercent");
  return 1;
 }
 if (std::strcmp(table,"GameSpeeds") == 0)
 {
  if (id<0 || id>=static_cast<int>(GC.getNumGameSpeedInfos())) return luaL_error(L,"info-cache index out of bounds");
  const CvGameSpeedInfo* info=GC.getGameSpeedInfo(static_cast<GameSpeedTypes>(id));
  if (!info) return luaL_error(L,"info-cache entry missing");
  lua_createtable(L,0,30);
  lua_pushinteger(L,info->getBarbPercent()); lua_setfield(L,-2,"BarbPercent");
  lua_pushinteger(L,info->getBuildPercent()); lua_setfield(L,-2,"BuildPercent");
  lua_pushinteger(L,info->getConstructPercent()); lua_setfield(L,-2,"ConstructPercent");
  lua_pushinteger(L,info->getCreatePercent()); lua_setfield(L,-2,"CreatePercent");
  lua_pushinteger(L,info->getCulturePercent()); lua_setfield(L,-2,"CulturePercent");
  lua_pushinteger(L,info->GetDealDuration()); lua_setfield(L,-2,"DealDuration");
  lua_pushinteger(L,info->getFaithPercent()); lua_setfield(L,-2,"FaithPercent");
  lua_pushinteger(L,info->getFeatureProductionPercent()); lua_setfield(L,-2,"FeatureProductionPercent");
  lua_pushinteger(L,info->getGoldGiftMod()); lua_setfield(L,-2,"GoldGiftMod");
  lua_pushinteger(L,info->getGoldPercent()); lua_setfield(L,-2,"GoldPercent");
  lua_pushinteger(L,info->getGoldenAgePercent()); lua_setfield(L,-2,"GoldenAgePercent");
  lua_pushinteger(L,info->getGreatPeoplePercent()); lua_setfield(L,-2,"GreatPeoplePercent");
  lua_pushinteger(L,info->getGrowthPercent()); lua_setfield(L,-2,"GrowthPercent");
  lua_pushinteger(L,info->getHurryPercent()); lua_setfield(L,-2,"HurryPercent");
  lua_pushinteger(L,info->getImprovementPercent()); lua_setfield(L,-2,"ImprovementPercent");
  lua_pushinteger(L,info->getInflationOffset()); lua_setfield(L,-2,"InflationOffset");
  lua_pushinteger(L,info->getInflationPercent()); lua_setfield(L,-2,"InflationPercent");
  lua_pushinteger(L,info->getLeaguePercent()); lua_setfield(L,-2,"LeaguePercent");
  lua_pushinteger(L,info->getMinorCivElectionFreqMod()); lua_setfield(L,-2,"MinorCivElectionFreqMod");
  lua_pushinteger(L,info->getOpinionDurationPercent()); lua_setfield(L,-2,"OpinionDurationPercent");
  lua_pushinteger(L,info->getPeaceDealDuration()); lua_setfield(L,-2,"PeaceDealDuration");
  lua_pushinteger(L,info->getRelationshipDuration()); lua_setfield(L,-2,"RelationshipDuration");
  lua_pushinteger(L,info->getReligiousPressureAdjacentCity()); lua_setfield(L,-2,"ReligiousPressureAdjacentCity");
  lua_pushinteger(L,info->getResearchPercent()); lua_setfield(L,-2,"ResearchPercent");
  lua_pushinteger(L,info->getSpyRatePercent()); lua_setfield(L,-2,"SpyRatePercent");
  lua_pushinteger(L,info->getTrainPercent()); lua_setfield(L,-2,"TrainPercent");
  lua_pushinteger(L,info->getUnitDiscoverPercent()); lua_setfield(L,-2,"UnitDiscoverPercent");
  lua_pushinteger(L,info->getUnitHurryPercent()); lua_setfield(L,-2,"UnitHurryPercent");
  lua_pushinteger(L,info->getUnitTradePercent()); lua_setfield(L,-2,"UnitTradePercent");
  lua_pushinteger(L,info->getVictoryDelayPercent()); lua_setfield(L,-2,"VictoryDelayPercent");
  return 1;
 }
 if (std::strcmp(table,"Eras") == 0)
 {
  if (id<0 || id>=static_cast<int>(GC.getNumEraInfos())) return luaL_error(L,"info-cache index out of bounds");
  const CvEraInfo* info=GC.getEraInfo(static_cast<EraTypes>(id));
  if (!info) return luaL_error(L,"info-cache entry missing");
  lua_createtable(L,0,32);
  lua_pushinteger(L,info->getBuildPercent()); lua_setfield(L,-2,"BuildPercent");
  lua_pushinteger(L,info->getBuildingMaintenancePercent()); lua_setfield(L,-2,"BuildingMaintenancePercent");
  lua_pushinteger(L,info->getConstructPercent()); lua_setfield(L,-2,"ConstructPercent");
  lua_pushinteger(L,info->getCreatePercent()); lua_setfield(L,-2,"CreatePercent");
  lua_pushinteger(L,info->getDiplpEmphasisLatePolicies()); lua_setfield(L,-2,"DiploEmphasisLatePolicies");
  lua_pushinteger(L,info->getDiploEmphasisReligion()); lua_setfield(L,-2,"DiploEmphasisReligion");
  lua_pushinteger(L,info->getEmbarkedUnitDefense()); lua_setfield(L,-2,"EmbarkedUnitDefense");
  lua_pushinteger(L,info->getEventChancePerTurn()); lua_setfield(L,-2,"EventChancePerTurn");
  lua_pushinteger(L,info->getFaithCostMultiplier()); lua_setfield(L,-2,"FaithCostMultiplier");
  lua_pushinteger(L,info->getFreePopulation()); lua_setfield(L,-2,"FreePopulation");
  lua_pushinteger(L,info->getGreatPeoplePercent()); lua_setfield(L,-2,"GreatPeoplePercent");
  lua_pushinteger(L,info->getGrowthPercent()); lua_setfield(L,-2,"GrowthPercent");
  lua_pushinteger(L,info->getImprovementPercent()); lua_setfield(L,-2,"ImprovementPercent");
  lua_pushinteger(L,info->getLeaguePercent()); lua_setfield(L,-2,"LeaguePercent");
  lua_pushboolean(L,info->isNoBarbUnits()); lua_setfield(L,-2,"NoBarbUnits");
  lua_pushboolean(L,info->isNoGoodies()); lua_setfield(L,-2,"NoGoodies");
  lua_pushboolean(L,info->isNoReligion()); lua_setfield(L,-2,"NoReligion");
  lua_pushinteger(L,info->getResearchAgreementCost()); lua_setfield(L,-2,"ResearchAgreementCost");
  lua_pushinteger(L,info->getResearchPercent()); lua_setfield(L,-2,"ResearchPercent");
  lua_pushinteger(L,info->getSpiesGrantedForEveryone()); lua_setfield(L,-2,"SpiesGrantedForEveryone");
  lua_pushinteger(L,info->getSpiesGrantedForPlayer()); lua_setfield(L,-2,"SpiesGrantedForPlayer");
  lua_pushinteger(L,info->getStartPercent()); lua_setfield(L,-2,"StartPercent");
  lua_pushinteger(L,info->getStartingCulture()); lua_setfield(L,-2,"StartingCulture");
  lua_pushinteger(L,info->getStartingDefenseUnits()); lua_setfield(L,-2,"StartingDefenseUnits");
  lua_pushinteger(L,info->getStartingExploreUnits()); lua_setfield(L,-2,"StartingExploreUnits");
  lua_pushinteger(L,info->getStartingGold()); lua_setfield(L,-2,"StartingGold");
  lua_pushinteger(L,info->getStartingUnitMultiplier()); lua_setfield(L,-2,"StartingUnitMultiplier");
  lua_pushinteger(L,info->getStartingWorkerUnits()); lua_setfield(L,-2,"StartingWorkerUnits");
  lua_pushinteger(L,info->getTradeRouteFoodBonusTimes100()); lua_setfield(L,-2,"TradeRouteFoodBonusTimes100");
  lua_pushinteger(L,info->getTradeRouteProductionBonusTimes100()); lua_setfield(L,-2,"TradeRouteProductionBonusTimes100");
  lua_pushinteger(L,info->getTrainPercent()); lua_setfield(L,-2,"TrainPercent");
  lua_pushinteger(L,info->getWarmongerPercent()); lua_setfield(L,-2,"WarmongerPercent");
  return 1;
 }
 if (std::strcmp(table,"Leaders") == 0)
 {
  if (id<0 || id>=static_cast<int>(GC.getNumLeaderHeadInfos())) return luaL_error(L,"info-cache index out of bounds");
  const CvLeaderHeadInfo* info=GC.getLeaderHeadInfo(static_cast<LeaderHeadTypes>(id));
  if (!info) return luaL_error(L,"info-cache entry missing");
  lua_createtable(L,0,13);
  lua_pushinteger(L,info->GetBoldness()); lua_setfield(L,-2,"Boldness");
  lua_pushinteger(L,info->GetChattiness()); lua_setfield(L,-2,"Chattiness");
  lua_pushinteger(L,info->GetDenounceWillingness()); lua_setfield(L,-2,"DenounceWillingness");
  lua_pushinteger(L,info->GetDiploBalance()); lua_setfield(L,-2,"DiploBalance");
  lua_pushinteger(L,info->GetDoFWillingness()); lua_setfield(L,-2,"DoFWillingness");
  lua_pushinteger(L,info->GetForgiveness()); lua_setfield(L,-2,"Forgiveness");
  lua_pushinteger(L,info->GetLoyalty()); lua_setfield(L,-2,"Loyalty");
  lua_pushinteger(L,info->GetMeanness()); lua_setfield(L,-2,"Meanness");
  lua_pushinteger(L,info->GetMinorCivCompetitiveness()); lua_setfield(L,-2,"MinorCivCompetitiveness");
  lua_pushinteger(L,info->GetNeediness()); lua_setfield(L,-2,"Neediness");
  lua_pushinteger(L,info->GetVictoryCompetitiveness()); lua_setfield(L,-2,"VictoryCompetitiveness");
  lua_pushinteger(L,info->GetWarmongerHate()); lua_setfield(L,-2,"WarmongerHate");
  lua_pushinteger(L,info->GetWonderCompetitiveness()); lua_setfield(L,-2,"WonderCompetitiveness");
  return 1;
 }
 if (std::strcmp(table,"Terrains") == 0)
 {
  if (id<0 || id>=static_cast<int>(GC.getNumTerrainInfos())) return luaL_error(L,"info-cache index out of bounds");
  const CvTerrainInfo* info=GC.getTerrainInfo(static_cast<TerrainTypes>(id));
  if (!info) return luaL_error(L,"info-cache entry missing");
  lua_createtable(L,0,5);
  lua_pushboolean(L,info->isFound()); lua_setfield(L,-2,"Found");
  lua_pushinteger(L,info->getInfluenceCost()); lua_setfield(L,-2,"InfluenceCost");
  lua_pushinteger(L,info->getSeeFromLevel()); lua_setfield(L,-2,"SeeFrom");
  lua_pushinteger(L,info->getSeeThroughLevel()); lua_setfield(L,-2,"SeeThrough");
  lua_pushboolean(L,info->isWater()); lua_setfield(L,-2,"Water");
  return 1;
 }
 if (std::strcmp(table,"Features") == 0)
 {
  if (id<0 || id>=static_cast<int>(GC.getNumFeatureInfos())) return luaL_error(L,"info-cache index out of bounds");
  const CvFeatureInfo* info=GC.getFeatureInfo(static_cast<FeatureTypes>(id));
  if (!info) return luaL_error(L,"info-cache entry missing");
  lua_createtable(L,0,25);
  lua_pushboolean(L,info->isAddsFreshWater()); lua_setfield(L,-2,"AddsFreshWater");
  lua_pushinteger(L,info->getAppearanceProbability()); lua_setfield(L,-2,"AppearanceProbability");
  lua_pushinteger(L,info->getDefenseModifier()); lua_setfield(L,-2,"Defense");
  lua_pushinteger(L,info->getDisappearanceProbability()); lua_setfield(L,-2,"DisappearanceProbability");
  lua_pushinteger(L,info->getEffectProbability()); lua_setfield(L,-2,"EffectProbability");
  lua_pushinteger(L,info->getFirstFinderGold()); lua_setfield(L,-2,"FirstFinderGold");
  lua_pushinteger(L,info->getGrowthProbability()); lua_setfield(L,-2,"Growth");
  lua_pushboolean(L,info->isImpassable()); lua_setfield(L,-2,"Impassable");
  lua_pushinteger(L,info->getInBorderHappiness()); lua_setfield(L,-2,"InBorderHappiness");
  lua_pushinteger(L,info->getInfluenceCost()); lua_setfield(L,-2,"InfluenceCost");
  lua_pushinteger(L,info->getMovementCost()); lua_setfield(L,-2,"Movement");
  lua_pushboolean(L,info->IsNaturalWonder()); lua_setfield(L,-2,"NaturalWonder");
  lua_pushboolean(L,info->isNoAdjacent()); lua_setfield(L,-2,"NoAdjacent");
  lua_pushboolean(L,info->isNoCity()); lua_setfield(L,-2,"NoCity");
  lua_pushboolean(L,info->isNoCoast()); lua_setfield(L,-2,"NoCoast");
  lua_pushboolean(L,info->isNoImprovement()); lua_setfield(L,-2,"NoImprovement");
  lua_pushboolean(L,info->isNoRiver()); lua_setfield(L,-2,"NoRiver");
  lua_pushboolean(L,info->isNukeImmune()); lua_setfield(L,-2,"NukeImmune");
  lua_pushinteger(L,info->getOccurrenceFrequency()); lua_setfield(L,-2,"OccurrenceFrequency");
  lua_pushboolean(L,info->isRequiresFlatlands()); lua_setfield(L,-2,"RequiresFlatlands");
  lua_pushboolean(L,info->isRequiresRiver()); lua_setfield(L,-2,"RequiresRiver");
  lua_pushboolean(L,info->IsRough()); lua_setfield(L,-2,"Rough");
  lua_pushinteger(L,info->getSeeThroughChange()); lua_setfield(L,-2,"SeeThrough");
  lua_pushinteger(L,info->getStartingLocationWeight()); lua_setfield(L,-2,"StartingLocationWeight");
  lua_pushboolean(L,info->isYieldNotAdditive()); lua_setfield(L,-2,"YieldNotAdditive");
  return 1;
 }
 if (std::strcmp(table,"Resources") == 0)
 {
  if (id<0 || id>=static_cast<int>(GC.getNumResourceInfos())) return luaL_error(L,"info-cache index out of bounds");
  const CvResourceInfo* info=GC.getResourceInfo(static_cast<ResourceTypes>(id));
  if (!info) return luaL_error(L,"info-cache entry missing");
  lua_createtable(L,0,22);
  lua_pushinteger(L,info->getAIObjective()); lua_setfield(L,-2,"AIObjective");
  lua_pushinteger(L,info->getAITradeModifier()); lua_setfield(L,-2,"AITradeModifier");
  lua_pushinteger(L,info->getConstAppearance()); lua_setfield(L,-2,"ConstAppearance");
  lua_pushboolean(L,info->isFlatlands()); lua_setfield(L,-2,"Flatlands");
  lua_pushinteger(L,info->getGroupRand()); lua_setfield(L,-2,"GroupRand");
  lua_pushinteger(L,info->getGroupRange()); lua_setfield(L,-2,"GroupRange");
  lua_pushinteger(L,info->getHappiness()); lua_setfield(L,-2,"Happiness");
  lua_pushboolean(L,info->isHills()); lua_setfield(L,-2,"Hills");
  lua_pushinteger(L,info->getMaxLatitude()); lua_setfield(L,-2,"MaxLatitude");
  lua_pushinteger(L,info->getMinAreaSize()); lua_setfield(L,-2,"MinAreaSize");
  lua_pushinteger(L,info->getMinLandPercent()); lua_setfield(L,-2,"MinLandPercent");
  lua_pushboolean(L,info->isNoRiverSide()); lua_setfield(L,-2,"NoRiverSide");
  lua_pushboolean(L,info->isNormalize()); lua_setfield(L,-2,"Normalize");
  lua_pushboolean(L,info->isOnlyMinorCivs()); lua_setfield(L,-2,"OnlyMinorCivs");
  lua_pushinteger(L,info->getPlacementOrder()); lua_setfield(L,-2,"PlacementOrder");
  lua_pushinteger(L,info->getPercentPerPlayer()); lua_setfield(L,-2,"Player");
  lua_pushinteger(L,info->getRandAppearance1()); lua_setfield(L,-2,"RandApp1");
  lua_pushinteger(L,info->getRandAppearance2()); lua_setfield(L,-2,"RandApp2");
  lua_pushinteger(L,info->getResourceUsage()); lua_setfield(L,-2,"ResourceUsage");
  lua_pushinteger(L,info->getTilesPer()); lua_setfield(L,-2,"TilesPer");
  lua_pushinteger(L,info->getUniqueRange()); lua_setfield(L,-2,"Unique");
  lua_pushinteger(L,info->getWonderProductionMod()); lua_setfield(L,-2,"WonderProductionMod");
  return 1;
 }
 if (std::strcmp(table,"Builds") == 0)
 {
  if (id<0 || id>=static_cast<int>(GC.getNumBuildInfos())) return luaL_error(L,"info-cache index out of bounds");
  const CvBuildInfo* info=GC.getBuildInfo(static_cast<BuildTypes>(id));
  if (!info) return luaL_error(L,"info-cache entry missing");
  lua_createtable(L,0,8);
  lua_pushboolean(L,info->IsCanBeEmbarked()); lua_setfield(L,-2,"CanBeEmbarked");
  lua_pushboolean(L,info->isKill()); lua_setfield(L,-2,"Kill");
  lua_pushboolean(L,info->IsRemoveRoute()); lua_setfield(L,-2,"RemoveRoute");
  lua_pushboolean(L,info->IsRemoveWaterCrossing()); lua_setfield(L,-2,"RemoveWaterCrossing");
  lua_pushboolean(L,info->isRepair()); lua_setfield(L,-2,"Repair");
  lua_pushboolean(L,info->IsSpecificCivRequired()); lua_setfield(L,-2,"SpecificCivRequired");
  lua_pushinteger(L,info->getTime()); lua_setfield(L,-2,"Time");
  lua_pushboolean(L,info->IsWater()); lua_setfield(L,-2,"Water");
  return 1;
 }
 if (std::strcmp(table,"Routes") == 0)
 {
  if (id<0 || id>=static_cast<int>(GC.getNumRouteInfos())) return luaL_error(L,"info-cache index out of bounds");
  const CvRouteInfo* info=GC.getRouteInfo(static_cast<RouteTypes>(id));
  if (!info) return luaL_error(L,"info-cache entry missing");
  lua_createtable(L,0,6);
  lua_pushinteger(L,info->getAdvancedStartCost()); lua_setfield(L,-2,"AdvancedStartCost");
  lua_pushinteger(L,info->getFlatMovementCost()); lua_setfield(L,-2,"FlatMovement");
  lua_pushinteger(L,info->GetGoldMaintenance()); lua_setfield(L,-2,"GoldMaintenance");
  lua_pushboolean(L,info->IsIndustrial()); lua_setfield(L,-2,"Industrial");
  lua_pushinteger(L,info->getMovementCost()); lua_setfield(L,-2,"Movement");
  lua_pushinteger(L,info->getValue()); lua_setfield(L,-2,"Value");
  return 1;
 }
 if (std::strcmp(table,"GameOptions") == 0)
 {
  if (id<0 || id>=static_cast<int>(GC.getNumGameOptionInfos())) return luaL_error(L,"info-cache index out of bounds");
  const CvGameOptionInfo* info=GC.getGameOptionInfo(static_cast<GameOptionTypes>(id));
  if (!info) return luaL_error(L,"info-cache entry missing");
  lua_createtable(L,0,2);
  lua_pushboolean(L,info->getDefault()); lua_setfield(L,-2,"Default");
  lua_pushboolean(L,info->getVisible()); lua_setfield(L,-2,"Visible");
  return 1;
 }
 if (std::strcmp(table,"PolicyBranchTypes") == 0)
 {
  if (id<0 || id>=static_cast<int>(GC.getNumPolicyBranchInfos())) return luaL_error(L,"info-cache index out of bounds");
  const CvPolicyBranchEntry* info=GC.getPolicyBranchInfo(static_cast<PolicyBranchTypes>(id));
  if (!info) return luaL_error(L,"info-cache entry missing");
  lua_createtable(L,0,7);
  lua_pushboolean(L,info->IsDelayWhenNoCityStates()); lua_setfield(L,-2,"AIDelayNoCityStates");
  lua_pushboolean(L,info->IsDelayWhenNoReligion()); lua_setfield(L,-2,"AIDelayNoReligion");
  lua_pushboolean(L,info->IsDelayWhenNoScience()); lua_setfield(L,-2,"AIDelayNoScience");
  lua_pushinteger(L,info->GetFirstAdopterFreePolicies()); lua_setfield(L,-2,"FirstAdopterFreePolicies");
  lua_pushboolean(L,info->IsLockedWithoutReligion()); lua_setfield(L,-2,"LockedWithoutReligion");
  lua_pushboolean(L,info->IsPurchaseByLevel()); lua_setfield(L,-2,"PurchaseByLevel");
  lua_pushinteger(L,info->GetSecondAdopterFreePolicies()); lua_setfield(L,-2,"SecondAdopterFreePolicies");
  return 1;
 }
 return luaL_error(L,"unsupported info-cache table");
}
